
import type { CardRecord } from './types';

export const initialData: CardRecord[] = [
  {
    id: '1',
    staffId: '123456',
    companyName: 'Tech Innovators Inc.',
    primaryCardholderName: 'Alice Johnson',
    primaryCardNumberBarcode: '635666123456',
    magStripe: 'MS12345',
    add1: '123 Innovation Drive',
    add2: 'Suite 100',
    add3: 'Tech Park',
    add4: 'Silicon Valley',
    add5: 'USA',
    postcode: '94043',
    validFrom: new Date('2023-01-01'),
    expires: new Date('2025-12-31'),
    letterFlag: true,
    overseas: false,
    primaryCardIssueDate: new Date('2023-01-01'),
    fullCardNoInCirculation: '635666123456',
    primaryCardType: 'Corporate Plus',
    nextPrimaryCardToBeCharged: true,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '2',
    staffId: '678901',
    companyName: 'Global Solutions Ltd.',
    primaryCardholderName: 'Bob Williams',
    primaryCardNumberBarcode: '635666678901',
    magStripe: 'MS67890',
    add1: '456 Global Avenue',
    add2: 'Floor 20',
    add3: '',
    add4: 'London',
    add5: 'UK',
    postcode: 'E14 5HQ',
    validFrom: new Date('2022-06-15'),
    expires: new Date('2024-06-14'),
    letterFlag: false,
    overseas: true,
    primaryCardIssueDate: new Date('2022-06-15'),
    fullCardNoInCirculation: '635666678901',
    primaryCardType: 'Business Travel',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: 'Charlie Brown',
    cardNumber2: '635666678901-2',
    primaryReplacementCardIssueDate: new Date('2023-08-20'),
    primaryPartCardNumberBarcode: 'P-9876',
    active: false,
    reason: 'Card expired',
  },
  {
    id: '3',
    staffId: '234567',
    companyName: 'Creative Designs',
    primaryCardholderName: 'Diana Prince',
    primaryCardNumberBarcode: '635666234567',
    magStripe: 'MS23456',
    add1: '789 Artistry Alley',
    add2: '',
    add3: '',
    add4: 'Paris',
    add5: 'France',
    postcode: '75001',
    validFrom: new Date('2024-02-01'),
    expires: new Date('2026-01-31'),
    letterFlag: true,
    overseas: true,
    primaryCardIssueDate: new Date('2024-02-01'),
    fullCardNoInCirculation: '635666234567',
    primaryCardType: 'Creative Suite',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: false,
    reason: 'Left company',
  },
  {
    id: '4',
    staffId: '345678',
    companyName: 'Secure Logistics',
    primaryCardholderName: 'Ethan Hunt',
    primaryCardNumberBarcode: '635666345678',
    magStripe: 'MS34567',
    add1: '1 Secure Plaza',
    add2: '',
    add3: '',
    add4: 'New York',
    add5: 'USA',
    postcode: '10001',
    validFrom: new Date('2023-05-10'),
    expires: new Date('2025-05-09'),
    letterFlag: false,
    overseas: false,
    primaryCardIssueDate: new Date('2023-05-10'),
    fullCardNoInCirculation: '635666345678',
    primaryCardType: 'Standard',
    nextPrimaryCardToBeCharged: true,
    cardholderName2: 'Jane Hunt',
    cardNumber2: '635666345678-2',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '5',
    staffId: '456789',
    companyName: 'Health First',
    primaryCardholderName: 'Fiona Glenanne',
    primaryCardNumberBarcode: '635666456789',
    magStripe: 'MS45678',
    add1: '2 Wellness Way',
    add2: 'Building B',
    add3: '',
    add4: 'Miami',
    add5: 'USA',
    postcode: '33101',
    validFrom: new Date('2022-11-20'),
    expires: new Date('2023-11-19'),
    letterFlag: true,
    overseas: false,
    primaryCardIssueDate: new Date('2022-11-20'),
    fullCardNoInCirculation: '635666456789',
    primaryCardType: 'Health Perks',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: false,
    reason: 'Expired',
  },
  {
    id: '6',
    staffId: '567890',
    companyName: 'Green Energy Co',
    primaryCardholderName: 'George Green',
    primaryCardNumberBarcode: '635666567890',
    magStripe: 'MS56789',
    add1: '3 Sustainability Street',
    add2: '',
    add3: '',
    add4: 'Berlin',
    add5: 'Germany',
    postcode: '10115',
    validFrom: new Date('2024-03-15'),
    expires: new Date('2026-03-14'),
    letterFlag: true,
    overseas: true,
    primaryCardIssueDate: new Date('2024-03-15'),
    fullCardNoInCirculation: '635666567890',
    primaryCardType: 'Eco Plus',
    nextPrimaryCardToBeCharged: true,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '7',
    staffId: '678901',
    companyName: 'Pioneer Ventures',
    primaryCardholderName: 'Hannah Montana',
    primaryCardNumberBarcode: '635666678901',
    magStripe: 'MS67890',
    add1: '4 Frontier Road',
    add2: '',
    add3: '',
    add4: 'Austin',
    add5: 'USA',
    postcode: '73301',
    validFrom: new Date('2023-08-01'),
    expires: new Date('2025-07-31'),
    letterFlag: false,
    overseas: false,
    primaryCardIssueDate: new Date('2023-08-01'),
    fullCardNoInCirculation: '635666678901',
    primaryCardType: 'Venture',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '8',
    staffId: '789012',
    companyName: 'Oceanic Airlines',
    primaryCardholderName: 'Ian Somerhalder',
    primaryCardNumberBarcode: '635666789012',
    magStripe: 'MS78901',
    add1: '5 Skyway',
    add2: 'Terminal 3',
    add3: '',
    add4: 'Sydney',
    add5: 'Australia',
    postcode: '2000',
    validFrom: new Date('2022-10-05'),
    expires: new Date('2024-10-04'),
    letterFlag: true,
    overseas: true,
    primaryCardIssueDate: new Date('2022-10-05'),
    fullCardNoInCirculation: '635666789012',
    primaryCardType: 'Frequent Flyer',
    nextPrimaryCardToBeCharged: true,
    cardholderName2: 'Nina Dobrev',
    cardNumber2: '635666789012-2',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: false,
    reason: 'Lost Card',
  },
  {
    id: '9',
    staffId: '890123',
    companyName: 'Stark Industries',
    primaryCardholderName: 'Jack Ryan',
    primaryCardNumberBarcode: '635666890123',
    magStripe: 'MS89012',
    add1: '6 Intelligence Ave',
    add2: '',
    add3: '',
    add4: 'Langley',
    add5: 'USA',
    postcode: '22101',
    validFrom: new Date('2024-01-20'),
    expires: new Date('2026-01-19'),
    letterFlag: false,
    overseas: false,
    primaryCardIssueDate: new Date('2024-01-20'),
    fullCardNoInCirculation: '635666890123',
    primaryCardType: 'Top Secret',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '10',
    staffId: '901234',
    companyName: 'Cyberdyne Systems',
    primaryCardholderName: 'Karen Page',
    primaryCardNumberBarcode: '635666901234',
    magStripe: 'MS90123',
    add1: '7 Skynet Street',
    add2: '',
    add3: '',
    add4: 'Sunnyvale',
    add5: 'USA',
    postcode: '94086',
    validFrom: new Date('2023-04-01'),
    expires: new Date('2025-03-31'),
    letterFlag: true,
    overseas: false,
    primaryCardIssueDate: new Date('2023-04-01'),
    fullCardNoInCirculation: '635666901234',
    primaryCardType: 'T-1000',
    nextPrimaryCardToBeCharged: true,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: new Date('2024-01-01'),
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '11',
    staffId: '112233',
    companyName: 'Wayne Enterprises',
    primaryCardholderName: 'Liam Neeson',
    primaryCardNumberBarcode: '635666112233',
    magStripe: 'MS11223',
    add1: '8 Batcave Blv',
    add2: '',
    add3: '',
    add4: 'Gotham',
    add5: 'USA',
    postcode: '10001',
    validFrom: new Date('2022-09-01'),
    expires: new Date('2024-08-31'),
    letterFlag: false,
    overseas: false,
    primaryCardIssueDate: new Date('2022-09-01'),
    fullCardNoInCirculation: '635666112233',
    primaryCardType: 'Vigilante',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: 'Christian Bale',
    cardNumber2: '635666112233-2',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: false,
    reason: 'Account Closed',
  },
  {
    id: '12',
    staffId: '223344',
    companyName: 'Umbrella Corporation',
    primaryCardholderName: 'Milla Jovovich',
    primaryCardNumberBarcode: '635666223344',
    magStripe: 'MS22334',
    add1: '9 Raccoon City',
    add2: 'The Hive',
    add3: '',
    add4: 'Raccoon City',
    add5: 'USA',
    postcode: '54321',
    validFrom: new Date('2024-04-04'),
    expires: new Date('2026-04-03'),
    letterFlag: true,
    overseas: false,
    primaryCardIssueDate: new Date('2024-04-04'),
    fullCardNoInCirculation: '635666223344',
    primaryCardType: 'Bio-weapon',
    nextPrimaryCardToBeCharged: true,
    cardholderName2: '',
    cardNumber2: '',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  {
    id: '13',
    staffId: '334455',
    companyName: 'Aperture Science',
    primaryCardholderName: 'Nolan North',
    primaryCardNumberBarcode: '635666334455',
    magStripe: 'MS33445',
    add1: '10 Portal Lane',
    add2: '',
    add3: '',
    add4: 'Gladstone',
    add5: 'USA',
    postcode: '49837',
    validFrom: new Date('2023-07-18'),
    expires: new Date('2025-07-17'),
    letterFlag: false,
    overseas: false,
    primaryCardIssueDate: new Date('2023-07-18'),
    fullCardNoInCirculation: '635666334455',
    primaryCardType: 'Test Subject',
    nextPrimaryCardToBeCharged: false,
    cardholderName2: 'Ellen McLain',
    cardNumber2: '635666334455-2',
    primaryReplacementCardIssueDate: undefined,
    primaryPartCardNumberBarcode: '',
    active: true,
  },
  ...Array.from({ length: 200 }, (_, i) => {
    const id = (14 + i).toString();
    const staffId = (100000 + i).toString();
    const name = `User ${i}`;
    const company = `Company ${String.fromCharCode(65 + (i % 26))}`;
    const country = i % 3 === 0 ? 'UK' : i % 3 === 1 ? 'USA' : 'Canada';
    const city = country === 'UK' ? 'London' : country === 'USA' ? 'New York' : 'Toronto';
    const active = Math.random() > 0.3;
    const expired = new Date() > new Date(2025, i % 12, (i % 28) + 1);
    
    return {
      id,
      staffId,
      companyName: company,
      primaryCardholderName: name,
      primaryCardNumberBarcode: `635666${staffId}`,
      magStripe: `MS${staffId}`,
      add1: `${i+1} Main St`,
      add2: '',
      add3: '',
      add4: city,
      add5: country,
      postcode: `${10000 + i}`,
      validFrom: new Date(2023, i % 12, (i % 28) + 1),
      expires: new Date(2025, i % 12, (i % 28) + 1),
      letterFlag: Math.random() > 0.5,
      overseas: country !== 'UK',
      primaryCardIssueDate: new Date(2023, i % 12, (i % 28) + 1),
      fullCardNoInCirculation: `635666${staffId}`,
      primaryCardType: 'Standard',
      nextPrimaryCardToBeCharged: Math.random() > 0.5,
      cardholderName2: '',
      cardNumber2: '',
      primaryReplacementCardIssueDate: undefined,
      primaryPartCardNumberBarcode: '',
      active: active && !expired,
      reason: !active ? (expired ? 'Expired' : 'Deactivated') : undefined,
    };
  }),
];

const julyRecords: CardRecord[] = [];
let currentId = 214;
for (let i = 0; i < 31; i++) {
    const currentDate = new Date(startDate);
    currentDate.setDate(startDate.getDate() + i);

    for (let j = 0; j < 3; j++) {
        const staffId = (300000 + currentId).toString();
        const name = `User July ${i+1}-${j+1}`;
        const company = `Company ${String.fromCharCode(65 + (currentId % 26))}`;
        const country = currentId % 3 === 0 ? 'UK' : currentId % 3 === 1 ? 'USA' : 'Canada';
        const city = country === 'UK' ? 'London' : country === 'USA' ? 'New York' : 'Toronto';
        const active = Math.random() > 0.3;
        const expired = new Date() > new Date(2025, currentDate.getMonth(), currentDate.getDate());

        julyRecords.push({
            id: currentId.toString(),
            staffId,
            companyName: company,
            primaryCardholderName: name,
            primaryCardNumberBarcode: `635666${staffId}`,
            magStripe: `MS${staffId}`,
            add1: `${currentId} Main St`,
            add2: '',
            add3: '',
            add4: city,
            add5: country,
            postcode: `${20000 + currentId}`,
            validFrom: currentDate,
            expires: new Date(2025, currentDate.getMonth(), currentDate.getDate()),
            letterFlag: Math.random() > 0.5,
            overseas: country !== 'UK',
            primaryCardIssueDate: currentDate,
            fullCardNoInCirculation: `635666${staffId}`,
            primaryCardType: 'Standard',
            nextPrimaryCardToBeCharged: Math.random() > 0.5,
            cardholderName2: '',
            cardNumber2: '',
            primaryReplacementCardIssueDate: undefined,
            primaryPartCardNumberBarcode: '',
            active: active && !expired,
            reason: !active ? (expired ? 'Expired' : 'Deactivated') : undefined,
        });
        currentId++;
    }
}
initialData.push(...julyRecords);

const july2025Records: CardRecord[] = [];
const startDateJuly2025 = new Date('2025-07-01');
for (let i = 0; i < 10; i++) {
    const currentDate = new Date(startDateJuly2025);
    currentDate.setDate(startDateJuly2025.getDate() + i);
    const staffId = (400000 + i).toString();
    const name = `Future User ${i+1}`;
    const company = `Company Future ${String.fromCharCode(65 + (i % 26))}`;
    const country = i % 2 === 0 ? 'UK' : 'USA';
    const city = country === 'UK' ? 'Manchester' : 'Chicago';
    july2025Records.push({
        id: (currentId + i).toString(),
        staffId,
        companyName: company,
        primaryCardholderName: name,
        primaryCardNumberBarcode: `635666${staffId}`,
        magStripe: `MS${staffId}`,
        add1: `${400 + i} Future Ave`,
        add2: '',
        add3: '',
        add4: city,
        add5: country,
        postcode: `${30000 + i}`,
        validFrom: currentDate,
        expires: new Date(2027, currentDate.getMonth(), currentDate.getDate()),
        letterFlag: Math.random() > 0.5,
        overseas: country !== 'UK',
        primaryCardIssueDate: currentDate,
        fullCardNoInCirculation: `635666${staffId}`,
        primaryCardType: 'Standard',
        nextPrimaryCardToBeCharged: Math.random() > 0.5,
        cardholderName2: '',
        cardNumber2: '',
        primaryReplacementCardIssueDate: undefined,
        primaryPartCardNumberBarcode: '',
        active: true,
    });
}
initialData.push(...july2025Records);
